import React, { useState, useEffect } from 'react';
import { Sidebar } from './components/Sidebar';
import { Dashboard } from './components/Dashboard';
import { PatientList } from './components/PatientList';
import { PatientDetail } from './components/PatientDetail';
import { PatientHistory } from './components/PatientHistory';
import { Settings } from './components/Settings';
import { Patient, PatientStatus } from './types';
import { getPatients, seedPatients } from './services/patientService';
import { MOCK_PATIENTS } from './constants';
import { Loader2, Database, RefreshCw, AlertTriangle, PlayCircle, Copy, Check } from 'lucide-react';

// SQL Schema for the user to run if table is missing
const SCHEMA_SQL = `-- Run this in your Supabase SQL Editor

create table if not exists public.patients (
  id bigint generated by default as identity primary key,
  mrn text not null,
  name text not null,
  age integer,
  gender text,
  admission_date date,
  diagnosis text,
  stage text,
  room_number text,
  status text,
  attending_physician text,
  radiation_plan jsonb,
  chemo_protocol jsonb,
  vitals_history jsonb default '[]'::jsonb,
  allergies text[] default '{}',
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Ensure image_url column exists (fixes "Could not find column" error)
alter table public.patients add column if not exists image_url text;

-- Reload schema cache to ensure PostgREST picks up the new column
NOTIFY pgrst, 'reload schema';

-- Enable Row Level Security
alter table public.patients enable row level security;

-- Create a policy allowing anonymous access (for demo purposes only)
create policy "Enable access for all users" on public.patients
  for all using (true) with check (true);`;

function App() {
  const [activeView, setActiveView] = useState<'dashboard' | 'patients' | 'history' | 'settings'>('dashboard');
  const [selectedPatient, setSelectedPatient] = useState<Patient | null>(null);
  const [patients, setPatients] = useState<Patient[]>([]);
  const [loading, setLoading] = useState(true);
  const [seeding, setSeeding] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [seedError, setSeedError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const fetchData = async () => {
    // Only show full page loader if we have no data at all
    if (patients.length === 0) setLoading(true);
    
    setError(null);
    try {
      const data = await getPatients();
      setPatients(data);
    } catch (err: any) {
      console.error("Fetch error caught in App:", err);
      setError(err.message || "Failed to connect to database");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const handleSeedData = async () => {
    setSeeding(true);
    setSeedError(null);
    const { success, error: apiError } = await seedPatients();
    if (success) {
      await fetchData();
    } else {
      setSeedError(apiError || "Failed to seed data");
    }
    setSeeding(false);
  };

  const loadDemoData = () => {
    setPatients(MOCK_PATIENTS);
    setError(null);
    setLoading(false);
  };

  const copySQL = () => {
    navigator.clipboard.writeText(SCHEMA_SQL);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleNavigate = (view: 'dashboard' | 'patients' | 'history' | 'settings') => {
    setActiveView(view);
    setSelectedPatient(null);
  };

  const handleSelectPatient = (patient: Patient) => {
    setSelectedPatient(patient);
  };

  const handlePatientUpdated = (updatedPatient: Patient) => {
      // Optimistically update the local patients list immediately
      setPatients(prevPatients => 
        prevPatients.map(p => p.id === updatedPatient.id ? updatedPatient : p)
      );

      if (selectedPatient?.id === updatedPatient.id) {
        setSelectedPatient(updatedPatient);
      }
  };

  const handlePatientDeleted = (id: string) => {
    setPatients(prev => prev.filter(p => p.id !== id));
    if (selectedPatient?.id === id) {
      setSelectedPatient(null);
    }
  };

  // Filter patients: Dashboard and List only show active patients (not discharged)
  const activePatients = patients.filter(p => p.status !== PatientStatus.DISCHARGED);

  // Check if the error is specifically about missing tables or schema mismatch
  const isMissingTableError = error && (
    error.includes("Could not find the table") || 
    (error.includes("relation") && error.includes("does not exist")) ||
    error.includes("image_url") // Handle missing column error as setup requirement
  );

  // Loading Screen
  if (loading && patients.length === 0 && !error) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-slate-50">
        <div className="text-center space-y-4">
          <Loader2 className="w-10 h-10 text-teal-600 animate-spin mx-auto" />
          <p className="text-slate-500 font-medium">Connecting to Oncology Database...</p>
        </div>
      </div>
    );
  }

  // Database Setup / Error Screen
  if (error && patients.length === 0) {
     if (isMissingTableError) {
       return (
         <div className="flex min-h-screen items-center justify-center bg-slate-50 p-4">
           <div className="max-w-2xl w-full bg-white rounded-2xl shadow-xl overflow-hidden">
             <div className="p-8 border-b border-slate-100">
               <div className="flex items-center gap-4 mb-4">
                 <div className="w-12 h-12 bg-amber-100 rounded-full flex items-center justify-center flex-shrink-0">
                   <Database className="w-6 h-6 text-amber-600" />
                 </div>
                 <div>
                   <h2 className="text-xl font-bold text-slate-900">Database Setup Required</h2>
                   <p className="text-slate-500 text-sm">The 'patients' table or columns are missing in your Supabase project.</p>
                 </div>
               </div>
               
               <div className="bg-slate-50 rounded-lg p-4 mb-6 border border-slate-200">
                 <p className="text-sm text-slate-700 mb-2 font-medium">1. Run this SQL in your Supabase SQL Editor:</p>
                 <div className="relative group">
                   <pre className="bg-slate-900 text-slate-50 p-4 rounded-lg text-xs font-mono overflow-x-auto h-48 clinical-scroll">
                     {SCHEMA_SQL}
                   </pre>
                   <button 
                     onClick={copySQL}
                     className="absolute top-2 right-2 p-2 bg-white/10 hover:bg-white/20 text-white rounded-md transition-colors backdrop-blur-sm"
                     title="Copy SQL"
                   >
                     {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                   </button>
                 </div>
                 <p className="text-xs text-slate-500 mt-2">This will create the table, add any missing columns (like image_url), and refresh the schema cache.</p>
               </div>

               <div className="flex gap-3 justify-end">
                 <button 
                   onClick={loadDemoData}
                   className="px-4 py-2 text-slate-500 hover:text-slate-700 font-medium text-sm"
                 >
                   Use Offline Demo Data
                 </button>
                 <button 
                   onClick={fetchData}
                   className="px-6 py-2 bg-teal-600 hover:bg-teal-700 text-white rounded-lg font-semibold transition-all flex items-center gap-2 shadow-sm"
                 >
                   <RefreshCw className="w-4 h-4" />
                   Retry Connection
                 </button>
               </div>
             </div>
           </div>
         </div>
       );
     }

     // Generic Error
     return (
       <div className="flex min-h-screen items-center justify-center bg-slate-50 p-4">
        <div className="max-w-md w-full bg-white rounded-2xl shadow-xl p-8 text-center space-y-6">
          <div className="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto">
            <AlertTriangle className="w-8 h-8 text-red-600" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-slate-900">Connection Error</h2>
            <p className="text-slate-500 mt-2 text-sm">{error}</p>
          </div>
          <div className="flex flex-col gap-3">
            <button 
              onClick={fetchData}
              className="w-full py-3 bg-slate-900 hover:bg-slate-800 text-white rounded-xl font-semibold transition-all flex items-center justify-center gap-2"
            >
              <RefreshCw className="w-4 h-4" />
              Retry Connection
            </button>
            <button 
              onClick={loadDemoData}
              className="w-full py-3 bg-white border border-slate-200 hover:bg-slate-50 text-slate-700 rounded-xl font-semibold transition-all flex items-center justify-center gap-2"
            >
              <PlayCircle className="w-4 h-4" />
              Use Demo Data (Offline)
            </button>
          </div>
        </div>
      </div>
     );
  }

  return (
    <div className="flex min-h-screen bg-slate-50 font-sans text-slate-900">
      <Sidebar 
        activeView={activeView} 
        onNavigate={handleNavigate} 
      />
      
      <main className="flex-1 ml-64 relative">
        {patients.length === 0 && !loading ? (
           <div className="flex flex-col items-center justify-center h-screen space-y-6">
             <div className="w-16 h-16 bg-slate-100 rounded-full flex items-center justify-center">
               <Database className="w-8 h-8 text-slate-400" />
             </div>
             <div className="text-center max-w-md px-6">
               <h2 className="text-xl font-bold text-slate-900">Database Connected but Empty</h2>
               <p className="text-slate-500 mt-2">
                 We successfully connected to Supabase, but found no patient records. 
                 Would you like to seed the database with sample oncology data?
               </p>
               {seedError && (
                 <div className="mt-4 p-3 bg-red-50 text-red-700 text-sm rounded-lg border border-red-100 flex items-center gap-2 text-left">
                   <AlertTriangle className="w-4 h-4 flex-shrink-0" />
                   {seedError}
                 </div>
               )}
             </div>
             <button 
               onClick={handleSeedData}
               disabled={seeding}
               className="flex items-center gap-2 px-6 py-3 bg-teal-600 hover:bg-teal-700 text-white rounded-xl font-semibold transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-lg shadow-teal-600/20"
             >
               {seeding ? <Loader2 className="w-5 h-5 animate-spin" /> : <RefreshCw className="w-5 h-5" />}
               {seeding ? 'Seeding Database...' : 'Seed Mock Data'}
             </button>
              <button 
                onClick={loadDemoData}
                className="text-sm text-slate-400 hover:text-slate-600 font-medium"
              >
                Skip & Use Local Demo Data
              </button>
           </div>
        ) : (
          <>
            {selectedPatient ? (
              <PatientDetail 
                patient={selectedPatient} 
                onBack={() => setSelectedPatient(null)}
                onPatientUpdated={handlePatientUpdated}
                onPatientDeleted={handlePatientDeleted}
              />
            ) : (
              <>
                {activeView === 'dashboard' && (
                  <Dashboard 
                    patients={activePatients}
                    onSelectPatient={handleSelectPatient}
                    onNavigatePatients={() => setActiveView('patients')}
                  />
                )}
                {activeView === 'patients' && (
                  <PatientList 
                    patients={activePatients}
                    onSelectPatient={handleSelectPatient} 
                    onRefresh={fetchData}
                  />
                )}
                {activeView === 'history' && (
                  <PatientHistory 
                    patients={patients} // Pass all, component filters for DISCHARGED
                    onRefresh={fetchData}
                  />
                )}
                {activeView === 'settings' && (
                  <Settings />
                )}
              </>
            )}
          </>
        )}
      </main>
    </div>
  );
}

export default App;